### ISSUE TITLE
US.01 - Click the Peer Assessment Button

### ISSUE THREAD

**Issue by KevinMandiouba** [SOEN341Fall2024/TeamXL-SOEN341_Project_F24#84]
**User Story Description**

As a student, I want to click the Peer Assessment button on the student dashboard so that I can begin assessing my peers.

**User Acceptance Flow**

1. Student logs into the dashboard.
2. Student clicks on the "Peer Assessment" button.
3. Student is redirected to the peer selection page.

**Acceptance Criteria**

- [x] #93
- [x] #94

Story Points: 3

**Comment by Joyal99** [comment]
Button created successfully.

**Comment by KevinMandiouba** [comment]
Issue completed
